[versions]
# Plugins
kotlin = "2.2.10"
kotlin-coroutines = "1.10.2"
detekt = "1.23.8"
shadow = "8.3.6"
release-plugin = "3.1.0"
versions-plugin = "0.52.0"

# Testing
junit = "5.13.4"

# Logging
slf4j = "2.0.17"
logback = "1.5.18"

# Project Reactor
reactor-core = "3.7.9"
reactor-kotlin = "1.2.3"

# JDA
jda = "5.6.1"
# chewtils is pinned to 2.0 since 2.1 introduces a lot of deprecation warnings as a result of deprecating guildOnly, which is used in all our text commands
jda-chewtils = "2.0"
jda-ktx = "0.12.0"

# Parsing
jsoup = "1.21.1"
jackson = "2.19.2"

# Apache Commons
commons-lang = "3.18.0"
commons-configuration = "2.12.0"

# Networking
okhttp = "4.12.0"
retrofit = "3.0.0"
retrofit-reactor = "2.1.0"

# Database
jedis = "3.3.0"
mongodb = "5.5.1"
kmongo = "5.5.1"

# Database Migration
mongock-runner = "5.5.1"
mongock-driver = "5.5.1"

# Cache
caffeine = "3.2.2"

# Generation
xchart = "3.8.8"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
shadow = { id = "com.gradleup.shadow", version.ref = "shadow" }
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
release = { id = "net.researchgate.release", version.ref = "release-plugin" }
versions = { id = "com.github.ben-manes.versions", version.ref = "versions-plugin"}

[libraries]
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib-jdk8", version.ref = "kotlin" }
kotlin-reflect = { group = "org.jetbrains.kotlin", name = "kotlin-reflect", version.ref = "kotlin" }

coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
coroutines-reactor = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-reactor", version.ref = "kotlin-coroutines" }

detekt-formatting = { group = "io.gitlab.arturbosch.detekt", name = "detekt-formatting", version.ref = "detekt" }
detekt-cli = { group = "io.gitlab.arturbosch.detekt", name = "detekt-cli", version.ref = "detekt" }

junit-engine = { group = "org.junit.jupiter", name = "junit-jupiter-engine", version.ref = "junit" }
junit-params = { group = "org.junit.jupiter", name = "junit-jupiter-params", version.ref = "junit" }

slf4j-api = { group = "org.slf4j", name = "slf4j-api", version.ref = "slf4j" }
logback-classic = { group = "ch.qos.logback", name = "logback-classic", version.ref = "logback" }

reactor-core = { group = "io.projectreactor", name = "reactor-core", version.ref = "reactor-core" }
reactor-kotlin-extensions = { group = "io.projectreactor.kotlin", name = "reactor-kotlin-extensions", version.ref = "reactor-kotlin" }

jda = { group = "net.dv8tion", name = "JDA", version.ref = "jda" }
jda-chewtils = { group = "pw.chew", name = "jda-chewtils", version.ref = "jda-chewtils" }
jda-ktx = { group = "club.minnced", name = "jda-ktx", version.ref = "jda-ktx" }

jsoup = { group = "org.jsoup", name = "jsoup", version.ref = "jsoup" }

jackson-module-kotlin = { group = "com.fasterxml.jackson.module", name = "jackson-module-kotlin", version.ref = "jackson" }

commons-lang3 = { group = "org.apache.commons", name = "commons-lang3", version.ref = "commons-lang" }
commons-configuration2 = { group = "org.apache.commons", name = "commons-configuration2", version.ref = "commons-configuration" }

okhttp = { group = "com.squareup.okhttp3", name = "okhttp", version.ref = "okhttp" }
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
retrofit-jackson = { group = "com.squareup.retrofit2", name = "converter-jackson", version.ref = "retrofit" }
retrofit-reactor = { group = "com.jakewharton.retrofit", name = "retrofit2-reactor-adapter", version.ref = "retrofit-reactor" }

jedis = { group = "redis.clients", name = "jedis", version.ref = "jedis" }

mongodb-reactivestreams = { group = "org.mongodb", name = "mongodb-driver-reactivestreams", version.ref = "mongodb" }

kmongo = { group = "org.litote.kmongo", name = "kmongo", version.ref = "kmongo" }
kmongo-async = { group = "org.litote.kmongo", name = "kmongo-async", version.ref = "kmongo" }
kmongo-shared = { group = "org.litote.kmongo", name = "kmongo-shared", version.ref = "kmongo" }

mongock-standalone = { group = "io.mongock", name = "mongock-standalone", version.ref = "mongock-runner" }
mongock-driver = { group = "io.mongock", name = "mongodb-sync-v4-driver", version.ref = "mongock-driver" }

caffeine = { group = "com.github.ben-manes.caffeine", name = "caffeine", version.ref = "caffeine" }
xchart = { group = "org.knowm.xchart", name = "xchart", version.ref = "xchart" }
